<!doctype html>

<html lang="pt-BR">
<head>
    <meta name="format-detection" content="telephone=no">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, user-scalable=no">
    <meta name="resource-type" content="document">
    <meta name="classification" content="Internet">
    <meta name="distribution" content="Global">
    <meta name="language" content="pt-br" />
    <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
    <meta http-equiv="content-language" content="pt-br">
    <meta http-equiv="imagetoolbar" content="no">
    <meta name="MSSmartTagsPreventParsing" content="TRUE">
    <meta name="robots" content="ALL">
    <meta name="revisit-after" content="1 days">
    <meta name="author" content="CHP Soluções">

    <link href="<?= PUBLIC_URL ?>img/favicon.ico" rel="shortcut icon" type="image/x-icon">
    <title>Trafegus</title>

    <script type="text/javascript">
        PUBLIC_URL = "<?= PUBLIC_URL ?>";
        LANGUAGE = "<?= LANGUAGE ?>";
    </script>

    <link rel="stylesheet" type="text/css" href="<?= PUBLIC_URL; ?>css/estilo.min.css">

    <!--[if lt IE 9]>
    <script src="<?= PUBLIC_URL; ?>js/lib/html5shiv.js" async></script>
    <script src="<?= PUBLIC_URL; ?>js/lib/respond.min.js" async></script>
    <![endif]-->


    <script type="text/javascript" src="<?= PUBLIC_URL ?>js/lib/jquery-1.9.1.js"></script>
    <script type="text/javascript" src="<?= PUBLIC_URL ?>js/lib/bootstrap.js"></script>
    <script type="text/javascript" src="<?= PUBLIC_URL ?>js/lib/ripples.js"></script>
    <script type="text/javascript" src="<?= PUBLIC_URL ?>js/lib/material.js"></script>
    <script type="text/javascript" src="<?= PUBLIC_URL ?>js/layout/login.js"></script>
    <script type="text/javascript" src="<?= PUBLIC_URL ?>js/lib/bootstrap.js"></script>
    <script type="text/javascript" src="<?= PUBLIC_URL ?>js/lib/bootbox.min.js"></script>
    <script type="text/javascript" src="<?= PUBLIC_URL ?>js/lib/bootstrap-alert.js"></script>
    <script type="text/javascript">
        D = JSON.parse('<?= json_encode(include './module/Base/language/'.LANGUAGE.'/language.php') ?>');
    </script>

</head>
<body>
    <?php echo $this->content;?>

    <div id="container-alerts">
        <?php
        $messenger = new Zend\Session\Container('messenger');
        if ($messenger && $messenger->erro) { ?>
            <div class="alert-center alert alert-danger alert-dismissable fade in" role="alert">
                <a class="close" data-dismiss="alert" aria-label="close">&times;</a>
                <strong>Atenção!</strong> <?= $messenger->erro; $messenger->erro = null ?>
            </div>
        <?php }
        if ($messenger && $messenger->warn) { ?>
            <div class="alert-center alert alert-warning alert-dismissable fade in" role="alert">
                <a class="close" data-dismiss="alert" aria-label="close">&times;</a>
                <strong>Atenção!</strong> <?= $messenger->warn; $messenger->warn = null ?>
            </div>
        <?php }
        if($messenger && $messenger->msg){ ?>
            <div class="alert-center alert alert-success alert-dismissable fade in" role="alert">
                <a class="close" data-dismiss="alert" aria-label="close">&times;</a>
                <?= $messenger->msg; $messenger->msg = null ?>
            </div>
        <?php } ?>
    </div>
</body>
</html>
