<?php $sessao = new Zend\Session\Container('Session') ?>

<!doctype html>
<html lang="<?= LANGUAGE ?>">
<head>

    <meta name="format-detection" content="telephone=no">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <meta name="viewport" content="width=device-width, user-scalable=no">

    <meta name="resource-type" content="document">
    <meta name="classification" content="Internet">
    <meta name="distribution" content="Global">
    <meta name="language" content="<?= LANGUAGE ?>">
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="content-language" content="<?= LANGUAGE ?>">
    <meta http-equiv="imagetoolbar" content="no">
    <meta name="MSSmartTagsPreventParsing" content="TRUE">
    <meta name="robots" content="ALL">
    <meta name="revisit-after" content="1 days">
    <meta name="author" content="CHP Soluções">

    <title>Mapa Controle</title>

    <script type="text/javascript">
        WINDOW_OPEN = false;
        PUBLIC_URL = "<?= PUBLIC_URL ?>";
        LANGUAGE = "<?= LANGUAGE ?>";
        D = JSON.parse('<?= json_encode(include './module/Base/language/'.LANGUAGE.'/language.php') ?>');
        TIPO_BASE_MAPA = "osm";
        AGRUPAR_VEICULOS = "<?= $sessao->offsetGet('agruparVeiculos') ?>";
        URL_MAPA_OSM = "<?= $sessao->offsetGet('linkServidorOpenstreetMaps') ?>";
        URL_NOMINATIM = "<?= $sessao->offsetGet('linkOpenstreetMapsEnderecos') ?>";
        TIPO_EMPRESA = "<?= $sessao->offsetGet('tipoEmpresa') ?>";
        URL_ROTAS = "<?= $sessao->offsetGet('linkOpenstreetMapsRotas') ?>";
    </script>
    <link rel="stylesheet" type="text/css" href="<?= PUBLIC_URL ?>css/estilo.min.css">
    <link rel="stylesheet" type="text/css" href="<?= PUBLIC_URL ?>js/lib/bootstrap-treeview-master/src/css/bootstrap-treeview.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css"
          integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">




    <script type="text/javascript" src="<?= PUBLIC_URL ?>js/lib/jquery-1.12.4.js"></script>

    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">

    <script type="text/javascript" src="<?= PUBLIC_URL ?>js/lib/html5shiv.js"></script>
    <script type="text/javascript" src="<?= PUBLIC_URL ?>js/lib/respond.min.js"></script>
    <![endif]-->
    <script type="text/javascript" src="<?= PUBLIC_URL ?>js/lib/fontawesome-markers-master/fontawesome-markers.min.js"></script>
    <script type="text/javascript" src="<?= PUBLIC_URL ?>js/lib/jquery-1.12.4.js"></script>
    <script type="text/javascript" src="<?= PUBLIC_URL ?>js/lib/loading.js"></script>
    <script type="text/javascript" src="<?= PUBLIC_URL ?>js/lib/jquery.redirect-master/jquery.redirect.js"></script>
    <script type="text/javascript" src="<?= PUBLIC_URL ?>js/lib/moment.js"></script>
    <script type="text/javascript" src="<?= PUBLIC_URL ?>js/lib/bootstrap.js"></script>
    <script type="text/javascript" src="<?= PUBLIC_URL ?>js/lib/bootbox.min.js"></script>
    <script type="text/javascript" src="<?= PUBLIC_URL ?>js/lib/bootstrap-alert.js"></script>
    <script type="text/javascript" src="<?= PUBLIC_URL ?>js/lib/bootstrap-treeview-master/src/js/bootstrap-treeview.js"></script>
    <script type="text/javascript" src="<?= PUBLIC_URL ?>js/lib/bootstrap-editable.min.js"></script>
    <script type="text/javascript" src="<?= PUBLIC_URL ?>js/lib/bootstrap-datetimepicker.js"></script>
    <script type="text/javascript" src="<?= PUBLIC_URL ?>js/lib/bootstrap-validator.min.js" ></script>
<!--    <script type="text/javascript" src="--><?//= PUBLIC_URL ?><!--js/lib/load.js" ></script>-->
    <script type="text/javascript" src="<?= PUBLIC_URL ?>js/lib/main.js" ></script>
    <script type="text/javascript" src="<?= PUBLIC_URL ?>js/lib/highlight.js" ></script>
    <script type="text/javascript" src="<?= PUBLIC_URL ?>js/lib/bootstrap-switch.min.js" ></script>


    <script type="text/javascript" src="<?= PUBLIC_URL ?>js/lib/utils.js" ></script>

    <link rel="stylesheet" href="<?php echo PUBLIC_URL; ?>js/lib/jqwidgets/styles/jqx.base.css" type="text/css" />

    <script type="text/javascript" src="<?php echo PUBLIC_URL; ?>js/lib/jqwidgets/jqxcore.js"></script>
    <script type="text/javascript" src="<?php echo PUBLIC_URL; ?>js/lib/jqwidgets/jqxdata.js"></script>
    <script type="text/javascript" src="<?php echo PUBLIC_URL; ?>js/lib/jqwidgets/jqxbuttons.js"></script>
    <script type="text/javascript" src="<?php echo PUBLIC_URL; ?>js/lib/jqwidgets/globalization/globalize.js"></script>
    <script type="text/javascript" src="<?php echo PUBLIC_URL; ?>js/lib/jqwidgets/jqxscrollbar.js"></script>
    <script type="text/javascript" src="<?php echo PUBLIC_URL; ?>js/lib/jqwidgets/jqxmenu.js"></script>
    <script type="text/javascript" src="<?php echo PUBLIC_URL; ?>js/lib/jqwidgets/jqxgrid.js"></script>
    <script type="text/javascript" src="<?php echo PUBLIC_URL; ?>js/lib/jqwidgets/jqxgrid.selection.js"></script>
    <script type="text/javascript" src="<?php echo PUBLIC_URL; ?>js/lib/jqwidgets/jqxgrid.columnsresize.js"></script>
    <script type="text/javascript" src="<?php echo PUBLIC_URL; ?>js/lib/jqwidgets/jqxgrid.pager.js"></script>
    <script type="text/javascript" src="<?php echo PUBLIC_URL; ?>js/lib/jqwidgets/jqxgrid.sort.js"></script>
    <script type="text/javascript" src="<?php echo PUBLIC_URL; ?>js/lib/jqwidgets/jqxgrid.edit.js"></script>
    <script type="text/javascript" src="<?php echo PUBLIC_URL; ?>js/lib/jqwidgets/jqxlistbox.js"></script>
    <script type="text/javascript" src="<?php echo PUBLIC_URL; ?>js/lib/jqwidgets/jqxdropdownlist.js"></script>
    <script type="text/javascript" src="<?php echo PUBLIC_URL; ?>js/lib/jqwidgets/jqxdatetimeinput.js"></script>

    <script type="text/javascript" src="<?php echo PUBLIC_URL; ?>js/application/mapacontrole/utils.js"></script>
    <script type="text/javascript" src="<?= PUBLIC_URL ?>js/lib/ripples.js"></script>
    <script type="text/javascript" src="<?= PUBLIC_URL ?>js/lib/material.js"></script>
    <script type="text/javascript" src="<?= PUBLIC_URL ?>js/lib/modernizr2.6.2.min.js" ></script>

    <script type="text/javascript" src="<?= PUBLIC_URL ?>js/lib/select2.js"></script>
    <script type="text/javascript" src="<?= PUBLIC_URL ?>js/lib/select2Language.js"></script>
    <script type="text/javascript" src="<?= PUBLIC_URL ?>js/lib/chart.min.js"></script>



</head>
<body>
    <div id="wrapper">
        <div class="clearfix">	</div>
        <div class="container-fluid">

            <?= $this->content;?>

        </div>
        <div id="container-popovers"></div>
        <div id="container-modals"></div>
        <div id="container-select2"></div>
        <div id="container-alerts">
            <?php
            $messenger = new Zend\Session\Container('messenger');
            if ($messenger && $messenger->erro) { ?>
                <div class="alert-center alert alert-danger alert-dismissable fade in" role="alert">
                    <a class="close" data-dismiss="alert" aria-label="close">&times;</a>
                    <strong>Atenção!</strong> <?= $messenger->erro; $messenger->erro = null ?>
                </div>
            <?php }
            if ($messenger && $messenger->warn) { ?>
                <div class="alert-center alert alert-warning alert-dismissable fade in" role="alert">
                    <a class="close" data-dismiss="alert" aria-label="close">&times;</a>
                    <strong>Atenção!</strong> <?= $messenger->warn; $messenger->warn = null ?>
                </div>
            <?php }
            if($messenger && $messenger->msg){ ?>
                <div class="alert-center alert alert-success alert-dismissable fade in" role="alert">
                    <a class="close" data-dismiss="alert" aria-label="close">&times;</a>
                    <?= $messenger->msg; $messenger->msg = null ?>
                </div>
            <?php } ?>
        </div>

    </div>
    <div id="mainLoadingScreen" class="load-screen">
        <div class="load-container">
            <div class="sk-folding-cube">
                <div class="sk-cube1 sk-cube"></div>
                <div class="sk-cube2 sk-cube"></div>
                <div class="sk-cube4 sk-cube"></div>
                <div class="sk-cube3 sk-cube"></div>
            </div>
        </div>
    </div>
</body>
</html>