<!doctype html>
<html lang="<?= LANGUAGE ?>">
<head>

    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, user-scalable=no">
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

    <meta name="format-detection" content="telephone=no">

    <meta name="language" content="<?= LANGUAGE ?>">
    <meta http-equiv="content-language" content="<?= LANGUAGE ?>">
    <meta name="author" content="CHP Soluções">

    <title>Monitor GR</title>
    <style>
        html, body {
            height: 100%;
            margin: 0;
            padding: 0;
        }
    </style>
</head>
    <body>
        <?= $this->content;?>
    </body>
</html>
